export const GET_POSITION = 'GET_POSITION';
export const GET_CURRENT_CITY_WEATHER = 'GET_CURRENT_CITY_WEATHER';
export const SET_CITY_NAME = 'SET_CITY_NAME';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const DELETE_FAVORITES = 'DELETE_FAVORITES';